BEGIN {
  OFS="\t";

  c["little"]="size";
  c["big"]="size";
  c["white"]="color";
  c["green"]="color";
  c["blue"]="color";
  c["red"]="color";
  c["good"]="char";
  c["bad"]="char";
  c["first"]="ord";
  c["yellow"]="color";
  c["good-CP"]="char";
  c["mean"]="char";
  c["old"]="age";
  c["new"]="age";
  c["ole"]="age";
  c["terrible"]="char";
  c["curious"]="char";
  c["nice"]="char";
  c["orange"]="color";
  c["different"]="other";
  c["small"]="size";
  c["black"]="color";
  c["tall"]="size";
  c["short"]="size";
  c["pretty"]="char";
  c["wild"]="other";
  c["last"]="ord";
  c["high"]="size";
  c["large"]="size";
  c["next"]="ord";
  c["huge"]="size";
  c["violent"]="char";
  c["loud"]="sound";
  c["big-CP"]="size";
  c["own"]="other";
  c["wide"]="shape";
  c["brown"]="color";
  c["final"]="ord";
  c["blonde"]="color";
  c["pink"]="color";
  c["round"]="shape";
  c["pretend"]="other";
  c["special"]="char";
  c["wrong"]="char";
  c["same"]="other";
  c["tiny"]="size";
  c["plastic"]="type";
  c["pleasant"]="char";
  c["sad"]="emot";
  c["happy"]="emot";
  c["fun"]="emot";
  c["straight"]="shape";
  c["fuzz-dn"]="material";
  c["help-dn"]="char";
  c["dry"]="other";
  c["wet"]="other";
  c["okay"]="char";
  c["fun-dn"]="char";
  c["right"]="dir";
  c["left"]="dir";
  c["front"]="dir";
  c["south"]="dir";
  c["north"]="dir";
  c["bit-dn"]="size";
  c["hot"]="temp";
  c["cold"]="temp";
  c["warm"]="temp";
  c["run-dn"]="other";
  c["terrific"]="char";
  c["dead"]="other";
  c["hard"]="material";
  c["bitsy"]="size";
  c["soft"]="material";
  c["goof-dn"]="char";
  c["western"]="dir";
  c["enough"]="other";
  c["real"]="other";
  c["great"]="char";
  c["loose"]="shape";
  c["teeny"]="size";
  c["square"]="shape";
  c["stuffy"]="other";
  c["good-SP"]="char";
  c["beautiful"]="char";
  c["love-dn"]="char";
  c["wooden"]="material";
  c["snow-dn"]="color";
  c["long"]="shape";
  c["back"]="dir";
  c["dirt-dn"]="material";
  c["clean"]="material";
  c["mud-dn"]="material";
  c["mat"]="emot";
  c["regular"]="other";
  c["real"]="other";
  c["normal"]="other";
  c["wicked"]="char";
  c["peculiar"]="char";
  c["little-CP"]="size";
  c["wise"]="char";
  c["grass-dn"]="material";
  c["whole"]="quant";
  c["complete"]="quant";
  c["smooth"]="material";
  c["fat"]="shape";
  c["angry"]="emot";
  c["big-SP"]="size";
  c["naughty"]="char";
  c["poor"]="char";
  c["fair"]="char";
  c["purple"]="color";
  c["grey"]="color";
  c["second"]="ord";
  c["rock-dn"]="material";
  c["nasty"]="char";
  c["itsy"]="size";
  c["french"]="nat";
  c["russian"]="nat";
  c["american"]="nat";
  c["fresh"]="other";

  c["just"]="X";
}

{
  if ($1 in c) {
    class=c[$1];
  } else {
    class="?";
  }

  if (class=="X")
    next;

  print $1, $2, class;
  # DEV
  # if (!class) print
}

